### PR TITLE
More mappings for organizations and locations

### PR DESCRIPTION
**Pull request by dwbutler**
Hi,

Thanks for creating Wikidata::Client! It was just what I needed!

This adds some more mappings that we needed for organizations and locations. Would you prefer that I add some corresponding specs? If so, where should they go? In `entity_spec.rb`?

Thanks!

### CODE REVIEW

**Comment by klacointe** [comment]
Hi, thanks for the PR.

Yes, you can add specs in the entity_spec.rb, it will be perfect :+1:

**Comment by dwbutler** [comment]
@klacointe I added some specs to cover properties of type `CommonsMedia`. I noticed that the specs don't make it a goal to cover every single mapped property. Do you think the current test coverage is sufficient? Thanks!

**Comment by klacointe** [comment]
Thanks!

**Comment by klacointe** [comment]
Integrated in https://rubygems.org/gems/wikidata-client/versions/0.0.9

**Comment by dwbutler** [comment]
Thanks!

**Pull request merged**
