### PR TITLE
Add `property_name` and `property_keys` to `Entity`

### PR DESCRIPTION
**Pull request by hanspolo**
Adding some methods that I think could be useful for working with properties.

### CODE REVIEW

**Comment by klacointe** [comment]
Thanks.

Can you check why the build is failing on jruby-head?

**Comment by hanspolo** [comment]
I'm trying to find the issue, but can't really see, what fails there.
The test fails at the call of `github`, and this is called multiple times by other tests, that work well.

**Comment by hanspolo** [comment]
I'm getting a little confused 😄

**Comment by klacointe** [comment]
Published https://rubygems.org/gems/wikidata-client/versions/0.0.11

**Pull request merged**
